import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

import StyledComponentsRegistry from '@/lib/registry'

import "./globals.css";
import MobileWrap from "@/templates/MobileWrap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoSansKR = Noto_Sans_KR({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={notoSansKR.className}>
      <body className={``}>
        <StyledComponentsRegistry>
          <MobileWrap>{children}</MobileWrap>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
