import type { Metadata } from "next";

import StyledComponentsRegistry from '@/lib/registry'

import "./globals.css";
import MobileWrap from "@/templates/MobileWrap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <StyledComponentsRegistry>
          <MobileWrap>{children}</MobileWrap>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
